"""Static content for Anam Cara: emotional modes, quiz questions, post-quiz reflections,
echo notes, coping suggestions, and curated anonymous stories.

All text intentionally avoids clinical diagnosis language, toxic positivity,
and triggering wording. Phrases are gentle, validating, and non-prescriptive.
"""

MODES = [
    {
        "slug": "confusion",
        "name": "Confusion",
        "tagline": "When the inside feels foggy.",
        "description": "For moments when thoughts feel scattered and nothing seems to make full sense.",
        "palette": "confusion",
    },
    {
        "slug": "anxiety",
        "name": "Anxiety",
        "tagline": "When the chest feels tight.",
        "description": "For moments of nervous energy, worry loops, and that quiet hum of unease.",
        "palette": "anxiety",
    },
    {
        "slug": "burnout",
        "name": "Burnout",
        "tagline": "When the candle has burned low.",
        "description": "For days when even small things feel like too much.",
        "palette": "burnout",
    },
    {
        "slug": "overthinking",
        "name": "Overthinking",
        "tagline": "When the mind won’t soften.",
        "description": "For moments your thoughts keep replaying without rest.",
        "palette": "overthinking",
    },
    {
        "slug": "loneliness",
        "name": "Loneliness",
        "tagline": "When the room feels quiet.",
        "description": "For times of feeling unseen, even when others are near.",
        "palette": "loneliness",
    },
    {
        "slug": "pressure",
        "name": "Pressure & Expectations",
        "tagline": "When the weight feels heavy.",
        "description": "For moments of carrying expectations that don’t always feel like yours.",
        "palette": "pressure",
    },
    {
        "slug": "exhaustion",
        "name": "Emotional Exhaustion",
        "tagline": "When feelings feel too full.",
        "description": "For when emotions feel worn thin and rest hasn’t reached the inside yet.",
        "palette": "exhaustion",
    },
    {
        "slug": "disconnected",
        "name": "Feeling Left Out",
        "tagline": "When you feel a little outside.",
        "description": "For moments of feeling distant from people you wish you felt close to.",
        "palette": "disconnected",
    },
    {
        "slug": "happiness",
        "name": "Happiness & Gratitude",
        "tagline": "When something gentle is here.",
        "description": "For softer moments of warmth, smallness, and quiet thankfulness.",
        "palette": "happiness",
    },
]

_OPEN_ENDED = "What do you think is affecting you the most right now? You can write freely — no one will judge it."

_QUIZ_OPTIONS = ["Rarely", "Sometimes", "Often", "Almost always"]


def _q(text):
    return {"text": text, "options": _QUIZ_OPTIONS, "type": "scale"}


QUIZZES = {
    "confusion": [
        _q("Lately, I notice my thoughts feel scattered."),
        _q("I find it hard to name what I am feeling."),
        _q("Decisions, even small ones, feel harder than usual."),
        _q("I feel like I’m moving without a clear direction."),
        _q("I question things I used to feel sure about."),
        _q("I feel a quiet fog around my mind."),
        _q("It’s hard to explain my feelings to others."),
        _q("I feel out of sync with myself."),
        _q("I sometimes feel I don’t fully know what I want."),
        _q("My emotions shift quickly without a clear reason."),
        _q("I feel uncertain about what to do next in my day."),
        _q("I feel like things around me don’t fully add up."),
        _q("I lose track of what was important to me."),
        _q("I find myself drifting in my own thoughts."),
        _q("I feel unsure of who I am right now."),
        _q("I want clarity, but it doesn’t arrive."),
        _q("I feel pulled in different directions inside."),
        _q("Quiet moments sometimes feel heavier than busy ones."),
        _q("I’d feel relieved if someone just understood."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "anxiety": [
        _q("My mind races faster than I’d like."),
        _q("I notice tension in my body without a clear reason."),
        _q("I imagine worst-case outcomes."),
        _q("It’s hard to sit still in quiet."),
        _q("Small things feel bigger than they probably are."),
        _q("I feel like I’m bracing for something."),
        _q("My breathing feels shallow sometimes."),
        _q("I worry about things I cannot change."),
        _q("I overthink conversations after they happen."),
        _q("Falling asleep takes longer than it used to."),
        _q("I feel restless even when I’m tired."),
        _q("My thoughts loop on the same worries."),
        _q("I feel uneasy without being able to explain why."),
        _q("I want to slow down but don’t know how."),
        _q("I anticipate things going wrong."),
        _q("It’s hard to fully relax."),
        _q("I feel my heart speed up at unexpected moments."),
        _q("I avoid situations that make me nervous."),
        _q("I’d like a gentle pause from this feeling."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "burnout": [
        _q("I feel tired in a way sleep doesn’t fully fix."),
        _q("Tasks that used to feel easy feel heavy now."),
        _q("I don’t feel excited by things I usually enjoy."),
        _q("My energy runs out earlier in the day."),
        _q("I feel like I’m running on empty."),
        _q("I want to step away from everything for a while."),
        _q("My motivation feels far away."),
        _q("I feel guilty for needing rest."),
        _q("I forget small things more often."),
        _q("I feel emotionally distant from what I do."),
        _q("Even fun feels like effort."),
        _q("I rush through things just to be done."),
        _q("I notice I’ve stopped looking forward to things."),
        _q("My patience runs thin quickly."),
        _q("My body feels tight or worn."),
        _q("I want quiet more than usual."),
        _q("I feel disconnected from my goals."),
        _q("I’d like permission to slow down."),
        _q("Resting doesn’t come easily, even when I try."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "overthinking": [
        _q("My thoughts replay the same scenes."),
        _q("I analyse small interactions long after they end."),
        _q("I struggle to let a thought go."),
        _q("My mind feels louder at night."),
        _q("I think about what I should have said."),
        _q("I imagine many possible outcomes at once."),
        _q("I question my choices repeatedly."),
        _q("I find it hard to trust what I feel."),
        _q("I look for hidden meanings in what people say."),
        _q("I rewrite memories in my head."),
        _q("I feel mentally tired from thinking."),
        _q("I struggle to enjoy the present."),
        _q("Quietness fills with thoughts I didn’t invite."),
        _q("I feel torn between options."),
        _q("I want my mind to feel softer."),
        _q("Small mistakes stay with me."),
        _q("I doubt my decisions after I make them."),
        _q("My thoughts feel heavier than the situation."),
        _q("I’d like one calm thought to stay."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "loneliness": [
        _q("I feel unseen, even around others."),
        _q("It’s hard to share what I’m really feeling."),
        _q("I scroll instead of reaching out."),
        _q("I feel like no one would understand."),
        _q("My phone feels louder than my company."),
        _q("I miss being known."),
        _q("I feel quiet inside crowded places."),
        _q("I want closeness but don’t know how to ask."),
        _q("Conversations feel shallow lately."),
        _q("I sometimes feel forgotten."),
        _q("It’s easier to stay silent."),
        _q("I feel like I’m on the edge of my friendships."),
        _q("I wish someone would just check on me."),
        _q("I feel alone with my thoughts."),
        _q("I don’t feel fully welcome anywhere."),
        _q("I keep my real feelings hidden."),
        _q("I feel disconnected from the people around me."),
        _q("Being alone feels different than being lonely."),
        _q("I’d like to be heard, gently."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "pressure": [
        _q("I feel I must always do more."),
        _q("Other people’s expectations feel heavy."),
        _q("I worry about disappointing someone."),
        _q("I push myself even when I’m tired."),
        _q("I feel my worth is tied to performance."),
        _q("I am compared to others often."),
        _q("Resting feels like falling behind."),
        _q("I hide my struggles to seem okay."),
        _q("I feel watched, even in quiet moments."),
        _q("My calendar feels heavier than my heart."),
        _q("I take on more than I can carry."),
        _q("I feel guilty for slowing down."),
        _q("I want to be enough as I am."),
        _q("Praise feels distant; criticism stays."),
        _q("I find it hard to say ‘no’."),
        _q("I forget to ask what I actually want."),
        _q("My breath feels held during the day."),
        _q("I’d like the weight to soften."),
        _q("I crave a day with no expectations."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "exhaustion": [
        _q("My feelings feel used up."),
        _q("I cry more easily, or not at all."),
        _q("Small problems land big."),
        _q("I feel emotionally numb at times."),
        _q("I don’t have energy for usual reactions."),
        _q("I want to be held by quiet."),
        _q("I feel like a phone at 2% battery."),
        _q("I struggle to comfort myself."),
        _q("I avoid heavy conversations."),
        _q("Even good news feels distant."),
        _q("I feel raw without a clear cause."),
        _q("I want time to feel things at my pace."),
        _q("My patience feels paper-thin."),
        _q("I want to rest somewhere safe."),
        _q("I feel like I’m carrying everyone else."),
        _q("My emotions feel out of order."),
        _q("I feel softer than I look."),
        _q("I’d like gentleness, not solutions."),
        _q("I want permission to feel without explaining."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "disconnected": [
        _q("I feel a little outside of my group."),
        _q("Plans seem to happen without me."),
        _q("I notice I’m not always thought of."),
        _q("I feel like I have to earn my place."),
        _q("I hold back from joining in."),
        _q("I worry I’m too much, or not enough."),
        _q("I miss feeling included."),
        _q("Online spaces sometimes make it worse."),
        _q("I compare my closeness to others’."),
        _q("I feel hesitant to reach out first."),
        _q("I want to belong without performing."),
        _q("I feel quiet in group chats."),
        _q("I’d like a steady friend nearby."),
        _q("I overthink whether to message someone."),
        _q("Being left out hurts more than I show."),
        _q("I sometimes feel invisible."),
        _q("I want to feel chosen, not just accepted."),
        _q("I’d like deeper connections."),
        _q("I’m gentler with my friends than with myself."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
    "happiness": [
        _q("I noticed something small and good today."),
        _q("I felt warmth from someone recently."),
        _q("I am grateful for a quiet moment."),
        _q("A song or scent made me pause kindly."),
        _q("I felt proud of something gentle I did."),
        _q("I felt seen by someone today."),
        _q("I rested a little, and it felt okay."),
        _q("I felt soft toward myself today."),
        _q("I noticed light somewhere familiar."),
        _q("I shared a small laugh."),
        _q("Something felt easier than expected."),
        _q("I want to remember this feeling."),
        _q("I felt safe in my own company."),
        _q("I felt the world be kind, just briefly."),
        _q("I made room for a slow breath."),
        _q("I felt curious instead of worried."),
        _q("Something I love came back to me."),
        _q("I felt connected to a small thing."),
        _q("I’d like to keep this softness."),
        {"text": _OPEN_ENDED, "type": "open"},
    ],
}


REFLECTIONS = {
    "confusion": {
        "headline": "It’s okay to not have all the answers yet.",
        "body": "You may be feeling foggy — like the edges of your thoughts haven’t fully arrived. Confusion is not a failure of clarity; sometimes it’s a quiet pause before understanding. You are allowed to not know, for now.",
        "echo": [
            "Your feelings are allowed to take their time.",
            "You don’t owe anyone a clear answer right now.",
            "Stillness can be a form of listening.",
        ],
        "coping": [
            "Drink a small glass of water, slowly.",
            "Write down three thoughts without trying to fix them.",
            "Step outside for a few minutes of fresh air.",
            "Let one decision wait until tomorrow.",
        ],
    },
    "anxiety": {
        "headline": "Your body is asking for a little softness.",
        "body": "You may be feeling tightly wound — like your mind is two steps ahead of your breath. Anxiety can be loud, but it doesn’t define you. You are allowed to slow down without needing a reason.",
        "echo": [
            "You are safe in this moment.",
            "Your breath can be a quiet companion.",
            "You don’t have to solve everything right now.",
        ],
        "coping": [
            "Try a slow 4-7-8 breath: in for 4, hold for 7, out for 8.",
            "Place a hand on your chest and notice the warmth.",
            "Step away from the screen for ten minutes.",
            "Listen to a song that has always felt safe.",
        ],
    },
    "burnout": {
        "headline": "Resting is not falling behind.",
        "body": "You may be feeling depleted — like your candle has burned softly and needs time to refill. Burnout is not weakness; it’s a body asking to be heard. You are allowed to pause without earning it.",
        "echo": [
            "You are not the sum of your output.",
            "Slowness is not the opposite of growth.",
            "Your rest matters as much as your effort.",
        ],
        "coping": [
            "Choose one task to release today.",
            "Eat something gentle and warm.",
            "Lie down for ten minutes without your phone.",
            "Tell someone trusted that you are tired.",
        ],
    },
    "overthinking": {
        "headline": "Your mind is trying to keep you safe — even when it gets loud.",
        "body": "You may be feeling stuck in a loop — replaying scenes that have already ended. Overthinking is often a quiet form of care turned inward. You are allowed to let a thought drift past without finishing it.",
        "echo": [
            "You don’t have to follow every thought.",
            "Not every question needs an answer tonight.",
            "Your worth is steady, even when your mind isn’t.",
        ],
        "coping": [
            "Write the thought down and close the notebook.",
            "Name five things you can see in the room.",
            "Take a slow walk without a destination.",
            "Set a gentle timer to ‘think later’.",
        ],
    },
    "loneliness": {
        "headline": "Feeling unseen is real — and you are not alone in it.",
        "body": "You may be feeling distant — like a quiet song in a noisy room. Loneliness isn’t a flaw; it’s the heart asking for closeness. You are allowed to want to be known.",
        "echo": [
            "Your presence matters, even when it’s quiet.",
            "You are worthy of soft company.",
            "Being human means missing connection sometimes.",
        ],
        "coping": [
            "Send a short message to someone you trust.",
            "Sit somewhere with gentle background sound.",
            "Write a letter you don’t have to send.",
            "Be your own kind voice for one moment today.",
        ],
    },
    "pressure": {
        "headline": "You are allowed to be more than what you achieve.",
        "body": "You may be feeling weighted — like everyone’s expectations are stitched into your day. Pressure often grows quietly. You are allowed to set down what isn’t yours to carry.",
        "echo": [
            "Your worth is not on a deadline.",
            "Being enough is not a performance.",
            "Soft days do not erase your progress.",
        ],
        "coping": [
            "Cross one item off without doing it.",
            "Say a kind ‘no’ today, if you can.",
            "Stretch slowly for one minute.",
            "Remind yourself: this hour does not define me.",
        ],
    },
    "exhaustion": {
        "headline": "Your feelings have been working hard.",
        "body": "You may be feeling emotionally worn — like a soft cloth that needs to be set down. Emotional exhaustion is not laziness; it’s evidence of how much you’ve been holding. You are allowed to be tender with yourself.",
        "echo": [
            "Feeling tired emotionally is a real kind of tired.",
            "You can rest without explaining why.",
            "You don’t have to be okay all at once.",
        ],
        "coping": [
            "Wrap up in something warm for a few minutes.",
            "Put your phone face-down for a while.",
            "Drink something warm, slowly.",
            "Whisper to yourself: ‘I’m doing my best.’",
        ],
    },
    "disconnected": {
        "headline": "You don’t have to earn your belonging.",
        "body": "You may be feeling on the edge — like you’re watching connection from just outside. Feeling left out is painful, and it’s also very human. You are allowed to want to be included.",
        "echo": [
            "Your softness is not a reason to be left out.",
            "You belong, even on the quiet days.",
            "Some closeness takes time to find you.",
        ],
        "coping": [
            "Reach out to one person without expectations.",
            "Spend a few minutes doing something just for you.",
            "Step away from feeds that make it heavier.",
            "Write down one thing you love about being you.",
        ],
    },
    "happiness": {
        "headline": "Soft moments deserve to be noticed.",
        "body": "You may be feeling a quiet warmth — small, but real. Gratitude doesn’t have to be loud to count. You are allowed to hold this gently and let it stay a little.",
        "echo": [
            "Small joys are still joys.",
            "You are allowed to feel light without guilt.",
            "Noticing gentleness is its own kind of strength.",
        ],
        "coping": [
            "Write down one thing that felt good today.",
            "Share the warm moment with someone if you’d like.",
            "Take a slow breath and smile at nothing in particular.",
            "Return to this feeling later if it fades.",
        ],
    },
}


CURATED_STORIES = {
    "confusion": "Someone wrote: ‘For weeks I couldn’t tell if I was sad or just tired. I stopped trying to name it, and slowly the fog lifted on its own. I was okay all along — just paused.’",
    "anxiety": "Someone wrote: ‘My chest used to tighten before school every morning. I learned to take one slow breath and tell myself: this feeling will pass like all the others. It always did.’",
    "burnout": "Someone wrote: ‘I thought I needed to push harder. Turns out I needed a quiet weekend with no plans. The world didn’t end. I came back gentler.’",
    "overthinking": "Someone wrote: ‘At night my mind would replay everything I’d said. I started writing the thoughts in a little notebook and closing it. They didn’t go away, but they got quieter.’",
    "loneliness": "Someone wrote: ‘I felt invisible at lunch for months. One day I texted an old friend just to say hi. They said they’d been feeling the same. We both cried a little and laughed a lot.’",
    "pressure": "Someone wrote: ‘Everyone expected me to be the strong one. I was scared to say I was tired. When I finally said it, the people who mattered stayed.’",
    "exhaustion": "Someone wrote: ‘I didn’t know feelings could get tired too. I gave myself a no-screen evening and cried a little for no reason. I felt lighter after.’",
    "disconnected": "Someone wrote: ‘I always felt like the outside friend. I stopped waiting to be invited and started making small plans of my own. Slowly, my circle got softer.’",
    "happiness": "Someone wrote: ‘I noticed sunlight on my desk and felt okay for ten whole minutes. I’m learning that good moments don’t need to be big to count.’",
}
